/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import BoxPositionController from "../components/boxPositionController";
import { useRef, useState } from "react";
import { PerspectiveCamera } from "three";
import Image from "next/image";
import Ball from "../components/threeObject/ball";
import PointLight from "../components/threeLight/pointLight";

export default function Home() {
  const canvasRef = useRef();
  const [boxX, setBoxX] = useState(0);
  const [boxY, setBoxY] = useState(0);
  const [boxZ, setBoxZ] = useState(-20);

  var perspectiveCamera = new PerspectiveCamera(50, 1, 0.1, 100);

  return (
    <div>
      <Head>
        <title>Next.js 3D Object</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={mainStyle}>
        <Image src="/img/space.jpg" layout="fill" />
        <div css={canvasStyle}>
          <Canvas camera={perspectiveCamera} ref={canvasRef}>
            <Ball position={[boxX, boxY, boxZ]} />
            {/* <Box position={[boxX, boxY, boxZ]} /> */}
            <directionalLight
              color={"#fff"}
              intensity={1}
              position={[1, 1, 1]}
            />
            <PointLight position={[boxX, boxY, boxZ]} canvasRef={canvasRef}/>
          </Canvas>
        </div>
        <BoxPositionController
          boxX={boxX}
          boxY={boxY}
          boxZ={boxZ}
          setBoxX={(boxX) => setBoxX(boxX)}
          setBoxY={(boxY) => setBoxY(boxY)}
          setBoxZ={(boxZ) => setBoxZ(boxZ)}
        />
      </main>
    </div>
  );
}

const mainStyle = css({
  display: "flex",
  flexDirection: "column",
});

const canvasStyle = css({
  height: "100vh",
  width: "100%",
});


